# Generated by Django 3.2.5 on 2021-07-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0030_auto_20201018_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Focus',
        ),
        migrations.DeleteModel(
            name='ProfessionalSkill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_category',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='Seminar',
        ),
        migrations.DeleteModel(
            name='TechnicalSkill',
        ),
        migrations.RemoveField(
            model_name='toolsandtech',
            name='project',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='ToolsAndTech',
        ),
    ]
